/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stri.ProjetJava;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SAI
 */
public class GUIConnexion extends javax.swing.JFrame {
    private Joueur player;
    private Vector<Partie> listPartie;
    
    /**
     * Creates new form GUIConnexion
     */
    public GUIConnexion() throws RemoteException, MalformedURLException, NotBoundException, InterruptedException{
        initComponents();
        
        Serveur serveurimplem = (Serveur)Naming.lookup("rmi://127.0.0.1/Serveur");
        this.player = new Joueur(serveurimplem);
        
        this.listPartie=serveurimplem.getListePartie();
        this.comboPartie.addItem("...");
        for(int i=0; i < listPartie.size();i++){
            this.comboPartie.addItem(this.listPartie.get(i).getNom());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        champPseudo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboPartie = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        champPartie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perudo v2.0");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Entrez votre pseudo :");

        champPseudo.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        champPseudo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setText("Choisissez votre partie :");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Démarrer !");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        label1.setText("Perudo v2.0");

        jLabel3.setText("Créer votre partie :");

        champPartie.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        champPartie.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(champPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(champPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(212, 212, 212))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(champPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboPartie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(champPartie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        GUI fenetre;
        String partie="";
        if(this.champPseudo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Eh tête en l'air, inscris ton nom wesh !");
        }else{
            this.player.setPseudo(this.champPseudo.getText());
        
            if(!this.champPartie.getText().equals("")){
                try {
                    partie=this.champPartie.getText();
                    this.player.getServeurImplem().rejoindrePartie(this.player, this.champPartie.getText());
                    
                    this.setVisible(false);
                    
                    this.player.setGUI(new GUI());
                    
                    //recuperer les joueurs connectes
                    String tmp="";
                    Vector <Client> players=new Vector<Client>();
                    players=this.player.getServeurImplem().getJoueursConnectes(partie);
                    for(int i=0;i<players.size();i++){
                        tmp+=players.get(i).getPseudo()+" | ";
                    }
                    this.player.getGUI().getListJoueurs().setText(tmp);
                    this.player.getGUI().setVisible(true);
                    
                    
                } catch (RemoteException ex) {
                    Logger.getLogger(GUIConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(!this.comboPartie.getSelectedItem().equals("...")){
                try {
                    partie=(String)this.comboPartie.getSelectedItem();
                    this.player.getServeurImplem().rejoindrePartie(this.player, (String) this.comboPartie.getSelectedItem());
                    
                    this.setVisible(false);
                    
                    this.player.setGUI(new GUI());
                    
                    //recuperer les joueurs connectes
                    String tmp="";
                    Vector <Client> players=new Vector<Client>();
                    players=this.player.getServeurImplem().getJoueursConnectes(partie);
                    for(int i=0;i<players.size();i++){
                        tmp+=players.get(i).getPseudo()+" | ";
                    }
                    this.player.getGUI().getListJoueurs().setText(tmp);
                    this.player.getGUI().setVisible(true);
                    
                } catch (RemoteException ex) {
                    Logger.getLogger(GUIConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(this.champPartie.getText().equals("") && this.comboPartie.getSelectedItem().equals("...")){
                JOptionPane.showMessageDialog(null, "Eh tête en l'air, choisis une partie wesh !");
            }
            
            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUIConnexion().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(GUIConnexion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(GUIConnexion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(GUIConnexion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(GUIConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField champPartie;
    private javax.swing.JTextField champPseudo;
    private javax.swing.JComboBox<String> comboPartie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
